### ISSUE TITLE
Set up NGINX reverse proxy sidecar container

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/tf-fargate-task#1]
In order for the client container to communicate with the backend, we need to set up a reverse proxy in the Fargate task definition. See https://aws.amazon.com/blogs/compute/nginx-reverse-proxy-sidecar-container-on-amazon-ecs/

**Comment by enflo** [comment]
Is the nginx proxy only for the client or for all three services?

**Comment by mannykary** [comment]
@enflo It would be for the client container to be able to connect to the backend container.
